name: Build on wasm

on:
  push:
    branches: [ da/11_3/xmake_dev ]
  workflow_dispatch:

jobs:
  linuxbuild:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: | 
          sudo apt-get update
          sudo apt-get install -y elvish
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      # Force xmake to a specific folder (for cache)
      - name: Set xmake global dir
        run: |
          echo "XMAKE_GLOBALDIR=${{ runner.workspace }}/.xmake-global" >> "${{ github.env }}"
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@test
      - name: update repo
        run: |
          xmake repo -u
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: cache xmake
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
            ${{ github.workspace }}/build/.build_cache
          key: ${{ runner.os }}-xmake-${{ hashFiles('**/xmake.lua') }}
      # Force xmake to a specific folder (for cache)
      - name: emscripten
        run: xrepo install -y emscripten
      - name: config
        run: xmake config --yes -p wasm -vD
      - name: build
        run: xmake build --yes -vD
      - name: test
        run: xmake run --yes -vD --group=tests
